In [4]:
import numpy as np

In [8]:
import time

In [14]:
arr=np.array([1,2,3,4])
lst=[1,2,3,4]
start_time=time.time()
print(arr+5)
end_time=time.time()
execution_time = end_time-start_time
print(f"\nExecution Time: {execution_time} Seconds")
print((x+5 for x in lst))


[6 7 8 9]

Execution Time: 0.0004990100860595703 Seconds
<generator object <genexpr> at 0x00000263FF1D4EE0>


In [15]:
print(arr**2)

[ 1  4  9 16]


In [16]:
print([x**2 for x in lst])

[1, 4, 9, 16]


In [17]:
#mean
np.mean(arr)

np.float64(2.5)

In [21]:
# even filter
print(arr[arr%2==0])
print([x for x in lst if x%2==0])

[2 4]
[2, 4]


In [24]:
a = [1,4,7,45]
b=[3,9,2,4]
print([x+y for x,y in zip(a,b)])

[4, 13, 9, 49]


In [26]:
print (np.array([[1,2],[3,4]]))
print([[1,2],[3,4]])

[[1 2]
 [3 4]]
[[1, 2], [3, 4]]


In [27]:
print(a+b)

[1, 4, 7, 45, 3, 9, 2, 4]


In [28]:
print([x+y for x,y in zip(a,b)])

[4, 13, 9, 49]


In [30]:
print(arr+1)

[2 3 4 5]


In [34]:
arr[arr>2]=0
print(arr)

[1 2 0 0]


In [51]:
lst=[1,2,3,4]
print([0 if x>2 else x for x in lst])

[1, 2, 0, 0]


In [52]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
print(arr[0])
print(arr[1])

0
1


In [56]:
arr[4]=10
arr

array([ 0,  1,  2,  3, 10,  5,  6,  7,  8,  9])

In [59]:
arr=np.linspace(0,10,5)
arr

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [62]:
print(arr[0])
print(arr[1])
print(arr[4])

0.0
2.5
10.0


In [64]:
arr[4]=99
arr

array([ 0. ,  2.5,  5. ,  7.5, 99. ])

In [76]:
arr=np.linspace(0,5)
arr

array([0.        , 0.10204082, 0.20408163, 0.30612245, 0.40816327,
       0.51020408, 0.6122449 , 0.71428571, 0.81632653, 0.91836735,
       1.02040816, 1.12244898, 1.2244898 , 1.32653061, 1.42857143,
       1.53061224, 1.63265306, 1.73469388, 1.83673469, 1.93877551,
       2.04081633, 2.14285714, 2.24489796, 2.34693878, 2.44897959,
       2.55102041, 2.65306122, 2.75510204, 2.85714286, 2.95918367,
       3.06122449, 3.16326531, 3.26530612, 3.36734694, 3.46938776,
       3.57142857, 3.67346939, 3.7755102 , 3.87755102, 3.97959184,
       4.08163265, 4.18367347, 4.28571429, 4.3877551 , 4.48979592,
       4.59183673, 4.69387755, 4.79591837, 4.89795918, 5.        ])

In [69]:
arr=np.arange(1,200,2)
arr

array([  1,   3,   5,   7,   9,  11,  13,  15,  17,  19,  21,  23,  25,
        27,  29,  31,  33,  35,  37,  39,  41,  43,  45,  47,  49,  51,
        53,  55,  57,  59,  61,  63,  65,  67,  69,  71,  73,  75,  77,
        79,  81,  83,  85,  87,  89,  91,  93,  95,  97,  99, 101, 103,
       105, 107, 109, 111, 113, 115, 117, 119, 121, 123, 125, 127, 129,
       131, 133, 135, 137, 139, 141, 143, 145, 147, 149, 151, 153, 155,
       157, 159, 161, 163, 165, 167, 169, 171, 173, 175, 177, 179, 181,
       183, 185, 187, 189, 191, 193, 195, 197, 199])

In [71]:
arr=np.linspace(1,200,5)
arr

array([  1.  ,  50.75, 100.5 , 150.25, 200.  ])

In [79]:
arr=np.linspace(1,200,5)
print("arange(0,10,5):",a)
arr = np.arange(0,10,5)
print("arange(0,10,5):",b)

arange(0,10,5): [1, 4, 7, 45]
arange(0,10,5): [3, 9, 2, 4]


In [85]:
print(np.arange(0.1,0.2))
print("\nlinspace with exact number of points")

[0.1]

linspace with exact number of points


In [87]:
print("\n number of elements:")
print("len(arange):",len(np.arange(0,10,2)))
print("len(linspace):",len(np.linspace(0,10,2)))


 number of elements:
len(arange): 5
len(linspace): 2


In [89]:
print("\nprecison check:")
arr=np.arange(0,1,0,1)
lin=np.linspace(0,1,10)
print("arange ")


precison check:


TypeError: Cannot interpret '1' as a data type

In [97]:
arr = np.arange(55,78)
arr

array([55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
       72, 73, 74, 75, 76, 77])

In [98]:
condition_arr = arr>65
arr

array([55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
       72, 73, 74, 75, 76, 77])

In [99]:
arr[condition_arr]

array([66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77])

In [100]:
arr[arr>65]

array([66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77])

In [108]:
print("\nValues between 57&62:\n",arr[(arr>57)&(arr>63)])


Values between 57&62:
 [64 65 66 67 68 69 70 71 72 73 74 75 76 77]


In [105]:
marks=np.array([67,85,33,32,23])
passed_boolean=marks>35
print(passed_boolean)
print(marks[passed_boolean])

[ True  True False False False]
[67 85]
